import random
name = input("Nhập tên bệnh nhân: ")
gender = input("Nhập giới tính: ")
year_of_birth = int(input("Nhập năm sinh: "))
phone = input("Nhập số điện thoại: ")
email = input("Nhập email: ")
initial_symptom = input("Nhập triệu chứng ban đầu: ")
price = float(input("Nhập chi phí khám: "))
randomNumber = random.randint(100, 999)
patient_id = f"BN{year_of_birth}{randomNumber}"
print("--- THẺ BỆNH NHÂN ---")
print(f"Mã BN      : {patient_id}")
print(f"Tên        : {name} ({type(name)})")
print(f"Giới tính  : {gender} ({type(gender)})")
print(f"Năm sinh   : {year_of_birth} ({type(year_of_birth)})")
print(f"Số điện thoại : {phone} ({type(phone)})")
print(f"Email      : {email} ({type(email)})")
print(f"Triệu chứng: {initial_symptom} ({type(initial_symptom)})")
print(f"Chi phí    : {price} VND ({type(price)})")